[tool.autopep8]
max_line_length = 99

[tool.pylint.masters]
jobs = 0

[tool.pylint.messages_control]
disable = [
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-function-docstring",
]

[tool.pylint.format]
expected-line-ending-format = "LF"
max-line-length = 99

[tool.pylint.miscellaneous]
notes = ["FIXME", "TODO"]
